### ISSUE TITLE
CSS of pe:tooltip conflicts with p:tooltip

### ISSUE THREAD

**Issue by Mobe91** [primefaces-extensions/primefaces-extensions.github.com#472]
The tooltip.css included when using `pe:tooltip` defines 
```css
.ui-tooltip{
    position:absolute;
    left:-28000px;
    top:-28000px;
    ...
}
```
whereas the standard components.css used when using `p:tooltip` only defines
```css
.ui-tooltip {
    position: absolute;
    display: none;
}
```
The effect of this is that `p:tooltip`s are not shown when used in combination with `pe:tooltip`.
