### ISSUE TITLE
Layout and ImageAreaSelect: Convert to Data URI for Images

### ISSUE THREAD

**Issue by melloware** [primefaces-extensions/primefaces-extensions.github.com#518]
At build time convert:

```css
.ui-layout-resizer-west-open-hover {
    background: url("#{resource['primefaces-extensions:layout/resizable-w.gif']}") repeat-y center;
}
```
To which prevents Image lookup and speeds up component loading.
```css
,.ui-layout-resizer-west-open-hover{
background:url("data:image/gif;base64,R0lGODlhBgDoA8IIACc3Z3WCrKaux7C4zrvB1cjN3dvg8fr6/CwAAAAABgDoAwAD/mhFI6HMwfYWndLmWDnulwZuoSd+6KmabOmS8CinbUy/84rftt7XOSAvuPMRf0WhcchcOpXQpBRJPVqb0Sp2en1yt1pvONslg8tfMXqcNqvP8LfcTW/b2fi1Pl7P8+97c4B/foKFfYGIhImDhoyHjYqOi5STlpKYkZqQnI+elZmdoJufl6SjoqapoaWsqK2nqrCrsa6yr7i3ura8tb60wLOfAAQAGQcDBw/ExhXIygbMx8nLxdPQ0s7U0dba2N0Kz8K5vcHkv+O76Ofm6u3l6fDs8evu9O/18vbz/Pv++gDzCcRH8J7BfgELIhx48B/DhQodRkzYkCLEig8lYpyYGNGixosgP4r0SLKjSY4oN6oMWTIlS4YJAAA7") repeat-y center
}
```
