### ISSUE TITLE
Sheet: row style class background-color not working

### ISSUE THREAD

**Issue by muhdkhokhar** [primefaces-extensions/primefaces-extensions.github.com#651]
Primeface sheet row style class background-color not working

.positive {color : red;background-color: yellow}

that does not work

**Comment by melloware** [comment]
Its being overriden by HandsonTable.  Just add !important like...
```css
.positive {color : red;background-color: yellow !important}
```
