### ISSUE TITLE
TimePicker: doesn't look okay with modern themes

### ISSUE THREAD

**Issue by jepsar** [primefaces-extensions/primefaces-extensions.github.com#723]
Go to https://www.primefaces.org/showcase-ext/sections/timePicker/basicUsage.jsf and switch to nova-light for example.

**Comment by melloware** [comment]
wow that looks terrible.  It looks OK in Omega though so I wonder what is missing as far as the new themes and styles?

**Comment by jepsar** [comment]
I'll look into it..

**Comment by melloware** [comment]
One thing that is missing is "ui-icon-clock"  Both Aristo and Omega have defined ui-icon-clock but none of the premium themes have it. I think the premium themes are definitely missing some stuff as its missing the "North" arrow icon.  I can make it work with PrimeIcons by adding this.

```css
body .pe-timepicker-trigger .ui-icon-clock {
	font-family: 'primeicons';
	speak: none;
	font-style: normal;
	font-weight: normal;
	font-variant: normal;
	text-transform: none;
	line-height: 1;
	display: inline-block;
	-webkit-font-smoothing: antialiased;
	-moz-osx-font-smoothing: grayscale;
	text-indent: 0px !important;
	text-align: center;
	background: none;
	display: inline-block;
	font-size: 1.25em;
}

body .pe-timepicker-trigger .ui-icon-clock:before {
	content: "\e940";
}

body .ui-button .ui-icon-triangle-1-n {
	font-family: 'primeicons';
	speak: none;
	font-style: normal;
	font-weight: normal;
	font-variant: normal;
	text-transform: none;
	line-height: 1;
	display: inline-block;
	-webkit-font-smoothing: antialiased;
	-moz-osx-font-smoothing: grayscale;
	text-indent: 0px !important;
	text-align: center;
	background: none;
	display: inline-block;
	font-size: 1.25em;
}

body .ui-button .ui-icon-triangle-1-n:before {
	content: "\e933";
}

body .ui-button .ui-icon-triangle-1-s {
    font-family: 'primeicons';
    speak: none;
    font-style: normal;
    font-weight: normal;
    font-variant: normal;
    text-transform: none;
    line-height: 1;
    display: inline-block;
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
    text-indent: 0px !important;
    text-align: center;
    background: none;
    display: inline-block;
    font-size: 1.25em;
}

body .ui-button .ui-icon-triangle-1-s:before {
    content: "\e930";
}
```

But that breaks Aristo and Omega if PrimeIcons is not included.

**Comment by jepsar** [comment]
> One thing that is missing is "ui-icon-clock" Both Aristo and Omega have defined ui-icon-clock but none of the premium themes have it. I think the premium themes are definitely missing some stuff as its missing the "North" arrow icon. I can make it work with PrimeIcons by adding this.

Isn't this something worth reporting at PF? Or do you think there went for a bare minimum when it came to support legacy icons?

**Comment by melloware** [comment]
Yeah I think it should be reported.  I understand not having the clock icon maybe but the North Arrow seems like they would need that for spinner etc.  But the way they looked like they styled they styled the spinner icons specifically with ui-spinner etc.

**Comment by melloware** [comment]
The problem is there is no real issue tracker for those premium themes.  See: https://github.com/primefaces/primefaces/issues/5206

**Comment by jepsar** [comment]
We could also load the icons like the modern themes do:
```
@import url("/contextPath/javax.faces.resource/primeicons/primeicons.css.xhtml?ln=primefaces&v=7.0");
```
And then simply replace `ui-icon-clock` with the PI equivalent.

And other option I was thinking of is detecting if a legacy theme is used in Java and based on that set the icon. We can also make that a EL function, so you could use that to set the submit button icon.

**Comment by melloware** [comment]
It looks like PrimeIcons comes in PrimeFaces JAR but users must include it in their page its not enabled by default with..
```xml
<!-- For Community Themes except 'Luna' and 'Nova' theme -->
        <h:outputStylesheet name="primeicons/primeicons.css" library="primefaces"/>
```

But I like your idea if you want to give it a shot?

**Comment by jepsar** [comment]
> But I like your idea if you want to give it a shot?

Do you mean the one about Java legacy theme check?

**Comment by melloware** [comment]
Yeah basically anything we can do to make this work for Aristo/Omega icon themes and Nova and Luna Font themes would be ideal.  I am open to suggestions.

**Comment by melloware** [comment]
Also I was wrong the premium themes use FontAwesome i believe not PrimeIcons.

**Comment by jepsar** [comment]
I'm trying this route. I the component, check based on the theme if we need to load PrimeIcons:
```
    public TimePicker() {
        setRendererType(DEFAULT_RENDERER);
        ThemeUtils.loadPrimeIconsIfNeeded();
    }
``` 
In ThemeUtils:
```
    public static boolean needsPrimeIcons(final String theme) {
        return !isPixelIconTheme(theme) && !isPrimeIconTheme(theme);
    }

    public static void loadPrimeIconsIfNeeded() {
        if (needsPrimeIcons(getTheme())) {
            ResourceUtils.addComponentResource(getFacesContext(), "primeicons/primeicons.css");
        }
    }
```
But I run into an issue reading the configured theme:
```
    protected static String getConfiguredTheme() {
        String themeParamValue = getPrimeApplicationContext().getConfig().getTheme();
        if (themeParamValue != null) {
            ELContext elContext = getELContext();
            ValueExpression ve = getApplication().getExpressionFactory()
                    .createValueExpression(elContext, themeParamValue, String.class);
            return (String) ve.getValue(elContext);
        }
        else {
            return DEFAULT_THEME;
        }
    }
```
This is basically the same code as is used in the PF [HeadRenderer](https://github.com/primefaces/primefaces/blob/ce3e365460f99d27bfcfc447852963aed0ad9604/src/main/java/org/primefaces/renderkit/HeadRenderer.java#L75-L87). The issue I'm having is when reading the theme from the ValueExpression (the showcase uses `#{empty userSettings ? 'omega' : userSettings.currentTheme.name}`) I get the previous value, while the HeadRenderer gets the correct value. Like the component is rendered in a different phase than the HeadRenderer. Does anyone know why? I could create a PR to show what I have so far (if that helps).

**Comment by melloware** [comment]
@jepsar Did you delete your last comment about getting the PF theme?  I can't find it?

**Comment by jepsar** [comment]
Yeah, I already figured out what was going wrong. The component's constructor is executed too early to handle dynamic themes (as used in the showcase). So I need to take a step back and rethink my solution. Here is what I had so far https://github.com/jepsar/pfe-core/commit/ab74c91a4956af6b0661ae2bc5c8a73376d672ff

**Comment by melloware** [comment]
I like where you are going but maybe a simpler option is in the JS side?   Detect the theme and add the style with jquery ?  Since the theme loaded on the page absolutely can't be incorrect and phase doesn't matter?

**Comment by jepsar** [comment]
How can you detect the theme using JavaScript? Is that possible if you use a combined resource handler?

**Comment by melloware** [comment]
Even with resource optimizer the theme script is never optimized.

```xml
<link type="text/css" rel="stylesheet" href="/primeext-showcase/javax.faces.resource/theme.css.jsf?ln=primefaces-omega" />
```

**Comment by melloware** [comment]
In PrimeFaces core.js they have this method for changing theme.

So maybe we could write one for getTheme();
```javascript
changeTheme: function(newTheme) {
            if(newTheme && newTheme !== '') {
                var themeLink = $('link[href*="' + PrimeFaces.RESOURCE_IDENTIFIER + '/theme.css"]');
                // portlet
                if (themeLink.length === 0) {
                    themeLink = $('link[href*="' + PrimeFaces.RESOURCE_IDENTIFIER + '=theme.css"]');
                }

                var themeURL = themeLink.attr('href'),
                    plainURL = themeURL.split('&')[0],
                    oldTheme = plainURL.split('ln=')[1],
                    newThemeURL = themeURL.replace(oldTheme, 'primefaces-' + newTheme);

                themeLink.attr('href', newThemeURL);
            }
        },
```

**Comment by melloware** [comment]
I just pushed a fix that seems to work. Can you please review this commit: https://github.com/primefaces-extensions/core/commit/1b046f47f60bcd41b7154dfeffc81ceb6c397af2

**Comment by jepsar** [comment]
> I just pushed a fix that seems to work. Can you please review this commit: [primefaces-extensions/core@1b046f4](https://github.com/primefaces-extensions/core/commit/1b046f47f60bcd41b7154dfeffc81ceb6c397af2)

This only fixes the icons and still leaves some styling issues.

**Comment by melloware** [comment]
Yep I wanted to get the hard part out of the way in determining whether to use primeicons or not, now that we have that we can add custom CSS to style based on knowing .ui-prime-icons it set.

**Comment by melloware** [comment]
Just and FYI I am using PrimeFaces Designer to design a new theme and to get TimePicker to look right in new themes I had to add this SCSS to the designer.

```css
.pe-timepicker-trigger {
    .ui-icon-clock {
        @include icon_override("\e940");
    }
}

.ui-timepicker {
    background-color: $panelContentBgColor;

    .ui-timepicker-table {
        background-color: $panelContentBgColor;
        color: $textColor;
    }

    .ui-timepicker-table td a {
        width: 2.0em;
        text-align: center;
       
        &.ui-state-active {
            color: $primaryTextColor;
            background-color: $primaryColor;
        }

        &.ui-state-default {
            border: 1px solid $inputBorderColor;
            padding: .286em;
            color: $textColor;
        }
    }

    td.ui-timepicker-minutes {
        padding-left: 4px;
        padding-right: 4px;
        padding-bottom: 4px;
        border-left: 1px solid $inputBorderColor;
    }
}
```
